#include "cpu.h"

const std::vector<CPU::Instruction> CPU::instruction_table =
{
	{ "BRK", &CPU::BRK, AddressingMode::IMP, 7 }, // 0x00
	{ "ORA", &CPU::ORA, AddressingMode::IDX, 6 }, // 0x01
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x02
	{ "???", &CPU::NOP, AddressingMode::IDX, 8 }, // 0x03
	{ "???", &CPU::NOP, AddressingMode::ZPG, 3 }, // 0x04
	{ "ORA", &CPU::ORA, AddressingMode::ZPG, 3 }, // 0x05
	{ "ASL", &CPU::ASL, AddressingMode::ZPG, 5 }, // 0x06
	{ "???", &CPU::NOP, AddressingMode::ZPG, 5 }, // 0x07
	{ "PHP", &CPU::PHP, AddressingMode::IMP, 3 }, // 0x08
	{ "ORA", &CPU::ORA, AddressingMode::IMM, 2 }, // 0x09
	{ "ASL", &CPU::ASL, AddressingMode::ACC, 2 }, // 0x0A
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x0B
	{ "???", &CPU::NOP, AddressingMode::ABS, 4 }, // 0x0C
	{ "ORA", &CPU::ORA, AddressingMode::ABS, 4 }, // 0x0D
	{ "ASL", &CPU::ASL, AddressingMode::ABS, 6 }, // 0x0E
	{ "???", &CPU::NOP, AddressingMode::ABS, 6 }, // 0x0F

	{ "BPL", &CPU::BPL, AddressingMode::REL, 2 }, // 0x10
	{ "ORA", &CPU::ORA, AddressingMode::IDY, 5 }, // 0x11
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x12
	{ "???", &CPU::NOP, AddressingMode::IDY, 8 }, // 0x13
	{ "???", &CPU::NOP, AddressingMode::ZPX, 4 }, // 0x14
	{ "ORA", &CPU::ORA, AddressingMode::ZPX, 4 }, // 0x15
	{ "ASL", &CPU::ASL, AddressingMode::ZPX, 6 }, // 0x16
	{ "???", &CPU::NOP, AddressingMode::ZPX, 6 }, // 0x17
	{ "CLC", &CPU::CLC, AddressingMode::IMP, 2 }, // 0x18
	{ "ORA", &CPU::ORA, AddressingMode::ABY, 4 }, // 0x19
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x1A
	{ "???", &CPU::NOP, AddressingMode::ABY, 7 }, // 0x1B
	{ "???", &CPU::NOP, AddressingMode::ABX, 4 }, // 0x1C
	{ "ORA", &CPU::ORA, AddressingMode::ABX, 4 }, // 0x1D
	{ "ASL", &CPU::ASL, AddressingMode::ABX, 7 }, // 0x1E
	{ "???", &CPU::NOP, AddressingMode::ABX, 7 }, // 0x1F

	{ "JSR", &CPU::JSR, AddressingMode::ABS, 6 }, // 0x20
	{ "AND", &CPU::AND, AddressingMode::IDX, 6 }, // 0x21
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x22
	{ "???", &CPU::NOP, AddressingMode::IDX, 8 }, // 0x23
	{ "BIT", &CPU::BIT, AddressingMode::ZPG, 3 }, // 0x24
	{ "AND", &CPU::AND, AddressingMode::ZPG, 3 }, // 0x25
	{ "ROL", &CPU::ROL, AddressingMode::ZPG, 5 }, // 0x26
	{ "???", &CPU::NOP, AddressingMode::ZPG, 5 }, // 0x27
	{ "PLP", &CPU::PLP, AddressingMode::IMP, 4 }, // 0x28
	{ "AND", &CPU::AND, AddressingMode::IMM, 2 }, // 0x29
	{ "ROL", &CPU::ROL, AddressingMode::ACC, 2 }, // 0x2A
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x2B
	{ "BIT", &CPU::BIT, AddressingMode::ABS, 4 }, // 0x2C
	{ "AND", &CPU::AND, AddressingMode::ABS, 4 }, // 0x2D
	{ "ROL", &CPU::ROL, AddressingMode::ABS, 6 }, // 0x2E
	{ "???", &CPU::NOP, AddressingMode::ABS, 6 }, // 0x2F

	{ "BMI", &CPU::BMI, AddressingMode::REL, 2 }, // 0x30
	{ "AND", &CPU::AND, AddressingMode::IDY, 5 }, // 0x31
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x32
	{ "???", &CPU::NOP, AddressingMode::IDY, 8 }, // 0x33
	{ "???", &CPU::NOP, AddressingMode::ZPX, 4 }, // 0x34
	{ "AND", &CPU::AND, AddressingMode::ZPX, 4 }, // 0x35
	{ "ROL", &CPU::ROL, AddressingMode::ZPX, 6 }, // 0x36
	{ "???", &CPU::NOP, AddressingMode::ZPX, 6 }, // 0x37
	{ "SEC", &CPU::SEC, AddressingMode::IMP, 2 }, // 0x38
	{ "AND", &CPU::AND, AddressingMode::ABY, 4 }, // 0x39
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x3A
	{ "???", &CPU::NOP, AddressingMode::ABY, 7 }, // 0x3B
	{ "???", &CPU::NOP, AddressingMode::ABX, 4 }, // 0x3C
	{ "AND", &CPU::AND, AddressingMode::ABX, 4 }, // 0x3D
	{ "ROL", &CPU::ROL, AddressingMode::ABX, 7 }, // 0x3E
	{ "???", &CPU::NOP, AddressingMode::ABX, 7 }, // 0x3F

	{ "RTI", &CPU::RTI, AddressingMode::IMP, 6 }, // 0x40
	{ "EOR", &CPU::EOR, AddressingMode::IDX, 6 }, // 0x41
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x42
	{ "???", &CPU::NOP, AddressingMode::IDX, 8 }, // 0x43
	{ "???", &CPU::NOP, AddressingMode::ZPG, 3 }, // 0x44
	{ "EOR", &CPU::EOR, AddressingMode::ZPG, 3 }, // 0x45
	{ "LSR", &CPU::LSR, AddressingMode::ZPG, 5 }, // 0x46
	{ "???", &CPU::NOP, AddressingMode::ZPG, 5 }, // 0x47
	{ "PHA", &CPU::PHA, AddressingMode::IMP, 3 }, // 0x48
	{ "EOR", &CPU::EOR, AddressingMode::IMM, 2 }, // 0x49
	{ "LSR", &CPU::LSR, AddressingMode::ACC, 2 }, // 0x4A
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x4B
	{ "JMP", &CPU::JMP, AddressingMode::ABS, 3 }, // 0x4C
	{ "EOR", &CPU::EOR, AddressingMode::ABS, 4 }, // 0x4D
	{ "LSR", &CPU::LSR, AddressingMode::ABS, 6 }, // 0x4E
	{ "???", &CPU::NOP, AddressingMode::ABS, 6 }, // 0x4F

	{ "BVC", &CPU::BVC, AddressingMode::REL, 2 }, // 0x50
	{ "EOR", &CPU::EOR, AddressingMode::IDY, 5 }, // 0x51
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x52
	{ "???", &CPU::NOP, AddressingMode::IDY, 8 }, // 0x53
	{ "???", &CPU::NOP, AddressingMode::ZPX, 4 }, // 0x54
	{ "EOR", &CPU::EOR, AddressingMode::ZPX, 4 }, // 0x55
	{ "LSR", &CPU::LSR, AddressingMode::ZPX, 6 }, // 0x56
	{ "???", &CPU::NOP, AddressingMode::ZPX, 6 }, // 0x57
	{ "CLI", &CPU::CLI, AddressingMode::IMP, 2 }, // 0x58
	{ "EOR", &CPU::EOR, AddressingMode::ABY, 4 }, // 0x59
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x5A
	{ "???", &CPU::NOP, AddressingMode::ABY, 7 }, // 0x5B
	{ "???", &CPU::NOP, AddressingMode::ABX, 4 }, // 0x5C
	{ "EOR", &CPU::EOR, AddressingMode::ABX, 4 }, // 0x5D
	{ "LSR", &CPU::LSR, AddressingMode::ABX, 7 }, // 0x5E
	{ "???", &CPU::NOP, AddressingMode::ABX, 7 }, // 0x5F

	{ "RTS", &CPU::RTS, AddressingMode::IMP, 6 }, // 0x60
	{ "ADC", &CPU::ADC, AddressingMode::IDX, 6 }, // 0x61
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x62
	{ "???", &CPU::NOP, AddressingMode::IDX, 8 }, // 0x63
	{ "???", &CPU::NOP, AddressingMode::ZPG, 3 }, // 0x64
	{ "ADC", &CPU::ADC, AddressingMode::ZPG, 3 }, // 0x65
	{ "ROR", &CPU::ROR, AddressingMode::ZPG, 5 }, // 0x66
	{ "???", &CPU::NOP, AddressingMode::ZPG, 5 }, // 0x67
	{ "PLA", &CPU::PLA, AddressingMode::IMP, 4 }, // 0x68
	{ "ADC", &CPU::ADC, AddressingMode::IMM, 2 }, // 0x69
	{ "ROR", &CPU::ROR, AddressingMode::ACC, 2 }, // 0x6A
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x6B
	{ "JMP", &CPU::JMP, AddressingMode::IND, 5 }, // 0x6C
	{ "ADC", &CPU::ADC, AddressingMode::ABS, 4 }, // 0x6D
	{ "ROR", &CPU::ROR, AddressingMode::ABS, 6 }, // 0x6E
	{ "???", &CPU::NOP, AddressingMode::ABS, 6 }, // 0x6F

	{ "BVS", &CPU::BVS, AddressingMode::REL, 2 }, // 0x70
	{ "ADC", &CPU::ADC, AddressingMode::IDY, 5 }, // 0x71
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x72
	{ "???", &CPU::NOP, AddressingMode::IDY, 8 }, // 0x73
	{ "???", &CPU::NOP, AddressingMode::ZPX, 4 }, // 0x74
	{ "ADC", &CPU::ADC, AddressingMode::ZPX, 4 }, // 0x75
	{ "ROR", &CPU::ROR, AddressingMode::ZPX, 6 }, // 0x76
	{ "???", &CPU::NOP, AddressingMode::ZPX, 6 }, // 0x77
	{ "SEI", &CPU::SEI, AddressingMode::IMP, 2 }, // 0x78
	{ "ADC", &CPU::ADC, AddressingMode::ABY, 4 }, // 0x79
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x7A
	{ "???", &CPU::NOP, AddressingMode::ABY, 7 }, // 0x7B
	{ "???", &CPU::NOP, AddressingMode::ABX, 4 }, // 0x7C
	{ "ADC", &CPU::ADC, AddressingMode::ABX, 4 }, // 0x7D
	{ "ROR", &CPU::ROR, AddressingMode::ABX, 7 }, // 0x7E
	{ "???", &CPU::NOP, AddressingMode::ABX, 7 }, // 0x7F

	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x80
	{ "STA", &CPU::STA, AddressingMode::IDX, 6 }, // 0x81
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x82
	{ "???", &CPU::NOP, AddressingMode::IDX, 6 }, // 0x83
	{ "STY", &CPU::STY, AddressingMode::ZPG, 3 }, // 0x84
	{ "STA", &CPU::STA, AddressingMode::ZPG, 3 }, // 0x85
	{ "STX", &CPU::STX, AddressingMode::ZPG, 3 }, // 0x86
	{ "???", &CPU::NOP, AddressingMode::ZPG, 3 }, // 0x87
	{ "DEY", &CPU::DEY, AddressingMode::IMP, 2 }, // 0x88
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x89
	{ "TXA", &CPU::TXA, AddressingMode::IMP, 2 }, // 0x8A
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0x8B
	{ "STY", &CPU::STY, AddressingMode::ABS, 4 }, // 0x8C
	{ "STA", &CPU::STA, AddressingMode::ABS, 4 }, // 0x8D
	{ "STX", &CPU::STX, AddressingMode::ABS, 4 }, // 0x8E
	{ "???", &CPU::NOP, AddressingMode::ABS, 4 }, // 0x8F

	{ "BCC", &CPU::BCC, AddressingMode::REL, 2 }, // 0x90
	{ "STA", &CPU::STA, AddressingMode::IDY, 6 }, // 0x91
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0x92
	{ "???", &CPU::NOP, AddressingMode::IDY, 6 }, // 0x93
	{ "STY", &CPU::STY, AddressingMode::ZPX, 4 }, // 0x94
	{ "STA", &CPU::STA, AddressingMode::ZPX, 4 }, // 0x95
	{ "STX", &CPU::STX, AddressingMode::ZPY, 4 }, // 0x96
	{ "???", &CPU::NOP, AddressingMode::ZPY, 4 }, // 0x97
	{ "TYA", &CPU::TYA, AddressingMode::IMP, 2 }, // 0x98
	{ "STA", &CPU::STA, AddressingMode::ABY, 5 }, // 0x99
	{ "TXS", &CPU::TXS, AddressingMode::IMP, 2 }, // 0x9A
	{ "???", &CPU::NOP, AddressingMode::ABY, 5 }, // 0x9B
	{ "???", &CPU::NOP, AddressingMode::ABX, 5 }, // 0x9C
	{ "STA", &CPU::STA, AddressingMode::ABX, 5 }, // 0x9D
	{ "???", &CPU::NOP, AddressingMode::ABY, 5 }, // 0x9E
	{ "???", &CPU::NOP, AddressingMode::ABY, 5 }, // 0x9F

	{ "LDY", &CPU::LDY, AddressingMode::IMM, 2 }, // 0xA0
	{ "LDA", &CPU::LDA, AddressingMode::IDX, 6 }, // 0xA1
	{ "LDX", &CPU::LDX, AddressingMode::IMM, 2 }, // 0xA2
	{ "???", &CPU::NOP, AddressingMode::IDX, 6 }, // 0xA3
	{ "LDY", &CPU::LDY, AddressingMode::ZPG, 3 }, // 0xA4
	{ "LDA", &CPU::LDA, AddressingMode::ZPG, 3 }, // 0xA5
	{ "LDX", &CPU::LDX, AddressingMode::ZPG, 3 }, // 0xA6
	{ "???", &CPU::NOP, AddressingMode::ZPG, 3 }, // 0xA7
	{ "TAY", &CPU::TAY, AddressingMode::IMP, 2 }, // 0xA8
	{ "LDA", &CPU::LDA, AddressingMode::IMM, 2 }, // 0xA9
	{ "TAX", &CPU::TAX, AddressingMode::IMP, 2 }, // 0xAA
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0xAB
	{ "LDY", &CPU::LDY, AddressingMode::ABS, 4 }, // 0xAC
	{ "LDA", &CPU::LDA, AddressingMode::ABS, 4 }, // 0xAD
	{ "LDX", &CPU::LDX, AddressingMode::ABS, 4 }, // 0xAE
	{ "???", &CPU::NOP, AddressingMode::ABS, 4 }, // 0xAF

	{ "BCS", &CPU::BCS, AddressingMode::REL, 2 }, // 0xB0
	{ "LDA", &CPU::LDA, AddressingMode::IDY, 5 }, // 0xB1
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0xB2
	{ "???", &CPU::NOP, AddressingMode::IDY, 5 }, // 0xB3
	{ "LDY", &CPU::LDY, AddressingMode::ZPX, 4 }, // 0xB4
	{ "LDA", &CPU::LDA, AddressingMode::ZPX, 4 }, // 0xB5
	{ "LDX", &CPU::LDX, AddressingMode::ZPY, 4 }, // 0xB6
	{ "???", &CPU::NOP, AddressingMode::ZPY, 4 }, // 0xB7
	{ "CLV", &CPU::CLV, AddressingMode::IMP, 2 }, // 0xB8
	{ "LDA", &CPU::LDA, AddressingMode::ABY, 4 }, // 0xB9
	{ "TSX", &CPU::TSX, AddressingMode::IMP, 2 }, // 0xBA
	{ "???", &CPU::NOP, AddressingMode::ABY, 4 }, // 0xBB
	{ "LDY", &CPU::LDY, AddressingMode::ABX, 4 }, // 0xBC
	{ "LDA", &CPU::LDA, AddressingMode::ABX, 4 }, // 0xBD
	{ "LDX", &CPU::LDX, AddressingMode::ABY, 4 }, // 0xBE
	{ "???", &CPU::NOP, AddressingMode::ABY, 4 }, // 0xBF

	{ "CPY", &CPU::CPY, AddressingMode::IMM, 2 }, // 0xC0
	{ "CMP", &CPU::CMP, AddressingMode::IDX, 6 }, // 0xC1
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0xC2
	{ "???", &CPU::NOP, AddressingMode::IDX, 8 }, // 0xC3
	{ "CPY", &CPU::CPY, AddressingMode::ZPG, 3 }, // 0xC4
	{ "CMP", &CPU::CMP, AddressingMode::ZPG, 3 }, // 0xC5
	{ "DEC", &CPU::DEC, AddressingMode::ZPG, 5 }, // 0xC6
	{ "???", &CPU::NOP, AddressingMode::ZPG, 5 }, // 0xC7
	{ "INY", &CPU::INY, AddressingMode::IMP, 2 }, // 0xC8
	{ "CMP", &CPU::CMP, AddressingMode::IMM, 2 }, // 0xC9
	{ "DEX", &CPU::DEX, AddressingMode::IMP, 2 }, // 0xCA
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0xCB
	{ "CPY", &CPU::CPY, AddressingMode::ABS, 4 }, // 0xCC
	{ "CMP", &CPU::CMP, AddressingMode::ABS, 4 }, // 0xCD
	{ "DEC", &CPU::DEC, AddressingMode::ABS, 6 }, // 0xCE
	{ "???", &CPU::NOP, AddressingMode::ABS, 6 }, // 0xCF

	{ "BNE", &CPU::BNE, AddressingMode::REL, 2 }, // 0xD0
	{ "CMP", &CPU::CMP, AddressingMode::IDY, 5 }, // 0xD1
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0xD2
	{ "???", &CPU::NOP, AddressingMode::IDY, 8 }, // 0xD3
	{ "???", &CPU::NOP, AddressingMode::ZPX, 4 }, // 0xD4
	{ "CMP", &CPU::CMP, AddressingMode::ZPX, 4 }, // 0xD5
	{ "DEC", &CPU::DEC, AddressingMode::ZPX, 6 }, // 0xD6
	{ "???", &CPU::NOP, AddressingMode::ZPX, 6 }, // 0xD7
	{ "CLD", &CPU::CLD, AddressingMode::IMP, 2 }, // 0xD8
	{ "CMP", &CPU::CMP, AddressingMode::ABY, 4 }, // 0xD9
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0xDA
	{ "???", &CPU::NOP, AddressingMode::ABY, 7 }, // 0xDB
	{ "???", &CPU::NOP, AddressingMode::ABX, 4 }, // 0xDC
	{ "CMP", &CPU::CMP, AddressingMode::ABX, 4 }, // 0xDD
	{ "DEC", &CPU::DEC, AddressingMode::ABX, 7 }, // 0xDE
	{ "???", &CPU::NOP, AddressingMode::ABX, 7 }, // 0xDF

	{ "CPX", &CPU::CPX, AddressingMode::IMM, 2 }, // 0xE0
	{ "SBC", &CPU::SBC, AddressingMode::IDX, 6 }, // 0xE1
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0xE2
	{ "???", &CPU::NOP, AddressingMode::IDX, 8 }, // 0xE3
	{ "CPX", &CPU::CPX, AddressingMode::ZPG, 3 }, // 0xE4
	{ "SBC", &CPU::SBC, AddressingMode::ZPG, 3 }, // 0xE5
	{ "INC", &CPU::INC, AddressingMode::ZPG, 5 }, // 0xE6
	{ "???", &CPU::NOP, AddressingMode::ZPG, 5 }, // 0xE7
	{ "INX", &CPU::INX, AddressingMode::IMP, 2 }, // 0xE8
	{ "SBC", &CPU::SBC, AddressingMode::IMM, 2 }, // 0xE9
	{ "NOP", &CPU::NOP, AddressingMode::IMP, 2 }, // 0xEA
	{ "???", &CPU::NOP, AddressingMode::IMM, 2 }, // 0xEB
	{ "CPX", &CPU::CPX, AddressingMode::ABS, 4 }, // 0xEC
	{ "SBC", &CPU::SBC, AddressingMode::ABS, 4 }, // 0xED
	{ "INC", &CPU::INC, AddressingMode::ABS, 6 }, // 0xEE
	{ "???", &CPU::NOP, AddressingMode::ABS, 6 }, // 0xEF

	{ "BEQ", &CPU::BEQ, AddressingMode::REL, 2 }, // 0xF0
	{ "SBC", &CPU::SBC, AddressingMode::IDY, 5 }, // 0xF1
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0xF2
	{ "???", &CPU::NOP, AddressingMode::IDY, 8 }, // 0xF3
	{ "???", &CPU::NOP, AddressingMode::ZPX, 4 }, // 0xF4
	{ "SBC", &CPU::SBC, AddressingMode::ZPX, 4 }, // 0xF5
	{ "INC", &CPU::INC, AddressingMode::ZPX, 6 }, // 0xF6
	{ "???", &CPU::NOP, AddressingMode::ZPX, 6 }, // 0xF7
	{ "SED", &CPU::SED, AddressingMode::IMP, 2 }, // 0xF8
	{ "SBC", &CPU::SBC, AddressingMode::ABY, 4 }, // 0xF9
	{ "???", &CPU::NOP, AddressingMode::IMP, 2 }, // 0xFA
	{ "???", &CPU::NOP, AddressingMode::ABY, 7 }, // 0xFB
	{ "???", &CPU::NOP, AddressingMode::ABX, 4 }, // 0xFC
	{ "SBC", &CPU::SBC, AddressingMode::ABX, 4 }, // 0xFD
	{ "INC", &CPU::INC, AddressingMode::ABX, 7 }, // 0xFE
	{ "???", &CPU::NOP, AddressingMode::ABX, 7 }  // 0xFF
};